import * as Crypto from 'expo-crypto';
import * as SecureStore from 'expo-secure-store';
import * as SQLite from 'expo-sqlite';

const DATABASE_NAME = 'onboard-engine.db';
const DATABASE_KEY_STORAGE = 'onboard.sqlite-cipher-key.v1';
let databasePromise: Promise<SQLite.SQLiteDatabase> | undefined;

async function getDatabaseKey(): Promise<string> {
  const existingKey = await SecureStore.getItemAsync(DATABASE_KEY_STORAGE);
  if (existingKey && /^[0-9a-f]{64}$/i.test(existingKey)) return existingKey;

  if (existingKey) {
    throw new Error('The local database key is invalid. Clear local app data to recover.');
  }

  const generated = await Crypto.AESEncryptionKey.generate(256);
  const key = await generated.encoded('hex');
  await SecureStore.setItemAsync(
    DATABASE_KEY_STORAGE,
    key,
    { keychainAccessible: SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY },
  );
  return key;
}

export function getEncryptedDatabase(): Promise<SQLite.SQLiteDatabase> {
  if (!databasePromise) databasePromise = openEncryptedDatabase();
  return databasePromise;
}

async function openEncryptedDatabase(): Promise<SQLite.SQLiteDatabase> {
  const key = await getDatabaseKey();
  const database = await SQLite.openDatabaseAsync(DATABASE_NAME);

  try {
    // This key is generated by the app and limited to hex characters before interpolation.
    await database.execAsync(`PRAGMA key = "x'${key}'"`);
    const cipher = await database.getFirstAsync<{ cipher_version?: string }>('PRAGMA cipher_version');
    if (!cipher?.cipher_version) {
      throw new Error('SQLCipher is required; build a native app with the configured prebuild settings.');
    }

    await database.execAsync(`
      PRAGMA journal_mode = WAL;
      PRAGMA foreign_keys = ON;
      CREATE TABLE IF NOT EXISTS sync_outbox (
        idempotency_key TEXT PRIMARY KEY NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('queued', 'sending', 'retry', 'synced', 'attention')),
        attempts INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        next_attempt_at INTEGER NOT NULL DEFAULT 0,
        pipeline_id TEXT,
        server_state TEXT,
        stage TEXT,
        error_code TEXT
      );
      CREATE INDEX IF NOT EXISTS sync_outbox_ready_idx
        ON sync_outbox(status, next_attempt_at, created_at);
      CREATE TABLE IF NOT EXISTS onboarding_draft (
        draft_id INTEGER PRIMARY KEY CHECK (draft_id = 1),
        first_name TEXT NOT NULL DEFAULT '',
        last_name TEXT NOT NULL DEFAULT '',
        email TEXT NOT NULL DEFAULT '',
        updated_at TEXT NOT NULL
      );
    `);
    return database;
  } catch (error) {
    await database.closeAsync();
    throw error;
  }
}
